### ISSUE TITLE
Call to undefined method Contao\Config::persist()

### ISSUE THREAD

**Issue by stefanschleich** [Craffft/contao-accountmail#5]
Beim Versuch die Extension über die Erweiterungsverwaltung zu installieren, erhalte ich direkt vor dem Datenbankupdate folgende Fehlermeldung:

`Fatal error: Call to undefined method Contao\Config::persist() in /opt/users/www/kd3web57web43/html/dedrone/system/modules/accountmail/library/Craffft/AccountMail/Updater.php on line 53`

System: Contao 3.2.16

**Comment by iCodr8** [comment]
`Contao\Config::persist() ` gab es erst ab Contao 3.3. Ich habe nun die Mindestanforderungen der Dependencies auf Contao 3.3.0 angepasst.
